#文件扩展名 c/cpp
EXTENSION = cpp
#编译命令
CXX = g++

#生成的文件名
EXE = main.exe

#源文件路径
SRC_PATH = .
#生成文件路径
EXE_PATH = exeFile
#头文件路径
INCLUDE_PATH = .
#包含的宏定义
DEFINE = XIAXDEFINE
#解决中文乱码
CHINESE = -fexec-charset=GB18030
#传入参数
CXXFLAGS = -Wall -g -I $(INCLUDE_PATH) -D $(DEFINE) $(CHINESE)

#删除文件的指令
RM = del /q

include C:\VSCode\C_Cpp_MinGW__VSCode\STUDY\Makefile
